import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import './styles/media-phone.css'
import './styles/general-and-levels.css'
import './styles/bords-styles.css'
import './styles/light-styles.css'
import './styles/light-animations.css'
import './styles/ships-styles.css'
import './styles/ships-animations.css'
import './styles/other-pics.css'
import './styles/other-pics-animations.css'

createApp(App).use(store).use(router).mount('#app')
